name: Deploy MkDocs with PDF

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install mkdocs mkdocs-material mkdocs-to-pdf

      - name: Build site
        run: mkdocs build

      - name: List built files
        run: ls -R site

      - name: Move PDF into site root
        run: |
          if [ -f TXRX-Doc-Hub/pdf/document.pdf ]; then
            mv TXRX-Doc-Hub/pdf/document.pdf TXRX-Doc-Hub/docs.pdf
          fi
        
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-pdf
          path: TXRX-Doc-Hub/docs.pdf
